# Generated by Django 3.2.7 on 2021-11-02 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('season', models.CharField(max_length=255, verbose_name='Рекомендуемый сезон для обуви')),
                ('gender', models.CharField(max_length=255, verbose_name='Пол')),
                ('size', models.CharField(max_length=255, verbose_name='Размер обуви')),
                ('top_material', models.CharField(max_length=255, verbose_name='Верхний материал')),
                ('sole_material', models.CharField(max_length=255, verbose_name='Материал подошвы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Summer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('season', models.CharField(max_length=255, verbose_name='Рекомендуемый сезон для обуви')),
                ('gender', models.CharField(max_length=255, verbose_name='Пол')),
                ('size', models.CharField(max_length=255, verbose_name='Размер обуви')),
                ('top_material', models.CharField(max_length=255, verbose_name='Верхний материал')),
                ('sole_material', models.CharField(max_length=255, verbose_name='Материал подошвы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
