# Generated by Django 3.2.7 on 2021-11-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211102_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summer',
            name='top_material',
            field=models.CharField(max_length=255, verbose_name='Материал верха'),
        ),
        migrations.AlterField(
            model_name='winter',
            name='top_material',
            field=models.CharField(max_length=255, verbose_name='Материал верха'),
        ),
    ]
