# Generated by Django 3.2.7 on 2021-11-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211103_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='size',
            field=models.CharField(choices=[('39', '39'), ('41', '41'), ('43', '43'), ('45', '45')], default=0, max_length=2, verbose_name='Размер обуви'),
        ),
    ]
