# Generated by Django 3.2.7 on 2021-11-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_cartproduct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='size',
            field=models.CharField(blank=True, choices=[('39', '39'), ('41', '41'), ('43', '43'), ('45', '45')], default=None, max_length=2, verbose_name='Размер обуви'),
        ),
    ]
