# Generated by Django 3.2.7 on 2021-11-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_cartproduct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='size',
            field=models.PositiveIntegerField(default=41),
        ),
    ]
