# Generated by Django 3.2.7 on 2021-11-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_cartproduct_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='summer',
            name='imagesecond',
            field=models.ImageField(default='', upload_to='', verbose_name='Второе Изображение'),
        ),
        migrations.AddField(
            model_name='summer',
            name='imagethird',
            field=models.ImageField(default='', upload_to='', verbose_name='Третье Изображение'),
        ),
        migrations.AddField(
            model_name='winter',
            name='imagesecond',
            field=models.ImageField(default='', upload_to='', verbose_name='Второе Изображение'),
        ),
        migrations.AddField(
            model_name='winter',
            name='imagethird',
            field=models.ImageField(default='', upload_to='', verbose_name='Третье Изображение'),
        ),
        migrations.AlterField(
            model_name='summer',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='winter',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Изображение'),
        ),
    ]
