# Generated by Django 3.2.7 on 2022-06-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20211105_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Winter',
            new_name='Kedi',
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина пользователя', 'verbose_name_plural': 'Корзина пользователей'},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'товар для корзины', 'verbose_name_plural': 'товары для корзины'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'покупатель', 'verbose_name_plural': 'покупатели'},
        ),
        migrations.AlterModelOptions(
            name='kedi',
            options={'verbose_name': 'Кеды', 'verbose_name_plural': 'Кеды'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='summer',
            options={'verbose_name': 'Летняя обувь', 'verbose_name_plural': 'Летняя обувь'},
        ),
    ]
