# Generated by Django 3.2.7 on 2022-06-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20220611_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kedi',
            new_name='Sneakers',
        ),
        migrations.AlterModelOptions(
            name='sneakers',
            options={'verbose_name': 'Кроссовки и кеды', 'verbose_name_plural': 'Кроссовки и кеды'},
        ),
    ]
