# Generated by Django 3.2.7 on 2022-06-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20220611_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summer',
            new_name='Boots',
        ),
        migrations.AlterModelOptions(
            name='boots',
            options={'verbose_name': 'Ботинки', 'verbose_name_plural': 'Ботинки'},
        ),
    ]
